name: Docker Image Build
on:
  push:
    branches:
    - non-existing-branch

jobs:

  build:

    runs-on: 
    - linux

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images using docker-compose
      run: docker-compose -f dc-base.yml build
